### ISSUE TITLE
intro page suggestion

### ISSUE THREAD

**Issue by xahlee** [mrkkrp/modalka#1]
hi, some suggestions.

• You have “Both packages don't have even 200 downloads and it's easy to explain. ”

Perhaps remove the “easy to explain” part. Because that seems to be “weasel words”.

for my xah-fly-keys, i put it on melpa just last week (2015-09-09), and it's for dvorak users only. 

• separate the Fingers and Xah Fly Keys so that each has its own heading. This is more easier for users to see and consistent with other package short reviews in your introduction.

• Consider adding ergoemacs-mode? It is on GNU Emacs ELPA. It has large user base, and precedes evil mode.

* add links to all your competing packages reviews? For example, i was curious about Fingers, but didn't find link.

PS I believe it is good for authors to say things about competitors. I have the same situation myself for my tutorial and packages, and it's often hard to write about. I think being more precise but honest, or even forceful, serves reader better. (or, perhaps don't mention competitors at all. I think most companies do this. Let users find out others and judge by themselves)

Just suggestions, not “issue” or “bug report”. Please don't feel obliged to address.

Thanks for mentioning xah fly keys too.

**Comment by mrkkrp** [comment]
@xahlee, Hi, thanks for the suggestions. I also appreciate some of your insights in Emacs “optimization”. Indeed, I see now that `xah-fly-keys` has been put on MELPA only recently. Actually judgment based on raw number of downloads is not perfect by itself, because as you said some packages may be optimized for keyboard layouts that are currently less popular (almost by definition) than traditional QWERTY, etc. Sorry for “easy to explain” part, no offence intended. I will definitely edit the README.md file.

Although about “efficiency” of particular layout in “normal” mode, I don't really think it makes difference. I feel that modal editing is easier than non-modal, but what exactly every key does and where it is placed is not that important, we can use “historical” conventions without any harm.

What do you think?

**Comment by xahlee** [comment]
@mrkkrp i think you are right that a modal way will solve emacs pinky for most people. But still, there's levels. For i think vast majority of programers (not just emacs or vim users, but all programers), modal is simply not familiar, and they will never go modal. Then, for emacs or vim hackers, i know many emacs uses who said they just can't get used to modal. This would rule out our packages for them. But the rest who likes modal, vi is well-known for decades, and i think that's good enough for 90% of people. Usually people don't want to learn new things, unless absolutely necessary. So, i think our audience is very small.

But for those who wants modal, for the choice of key/command map, they can go with vi convention, or your emacs style convention, or completely new design. I think we can't rank them in some absolute sense.

Again, thanks. I'll look at your mode. Very interesting.

**Comment by mrkkrp** [comment]
@xahlee, I want to improve my reviews and include mentioning of `god-mode` and `ergoemacs-mode`. Of course `xah-fly-keys` will get its separate section. About `ergoemacs-mode`, I know about this package, but I didn't know it provides something for modal editing. Is there some review or “help-section” for those who want to use `ergoemacs-mode` for modal editing? I would like to at least try it.

By the way there is a link for Fingers: https://github.com/fgeller/fingers.el

**Comment by mrkkrp** [comment]
@xahlee, just found [boon](https://github.com/jyp/boon), I think it may be interesting for you :-)

**Comment by xahlee** [comment]
@mrkkrp about ergoemacs-mode for modal, Matt F did have it, but am not sure what's the current status. At one point, i think he created a novel approach. That is, in em, you hold alt and the right side inverted T home row becomes arrow keys. At one point, there's a option one can turn on, such that when such arrow chord is invoked, it becomes modal, so that user no longer needs to hold Alt anymore. As soon as any none-movement command/key is called, it exit this modal mode.

not sure what's the current status though. Matt L @mlf176f2

**Comment by xahlee** [comment]
@mrkkrp thanks for boom and fingers. I'll create a list of all on my blog too.

**Comment by mrkkrp** [comment]
@xahlee, please share a link when it's done. I sometimes read your blog but I can forget or miss it. You can put the link here or feel free to send me email (email address is on my GitHub page).

**Comment by mlf176f2** [comment]
`ergoemacs-mode' supports modal editing.  It can even emulate `god-mode'.  You can either define your own modal keymap, or tell `ergoemacs-mode` that the keyboard layout is the same as the current layout, but with Alt (or control pressed, or swapped, or any sort of other key combination).

Ergoemacs-mode also "fights" with emacs, that is it defines different keys for next-line, previous line, etc.  However, it currently goes through and changes all of the active keymaps to match that key defintion.  Hence, if org-mode uses C-p for org-next-line, ergoemacs picks it up and then uses org next-line for the next line definition.  The key that is bound to <f6> by default, is defined as follows;
```
(ergoemacs-translation unchorded-alt ()
  "Make the Alt key sticky."
  :text "<Alt+>"
  :unchorded '(meta) 
  :shift '(meta shift)
  :meta '(meta shift) 
  :modal-color "red"
  :keymap-modal (let ((map (make-sparse-keymap)))
                  (define-key map (read-kbd-macro "<return>") 'ergoemacs-unchorded-alt-modal)
                  (define-key map (read-kbd-macro "RET") 'ergoemacs-unchorded-alt-modal)
                  map))
```

**Comment by mlf176f2** [comment]
It also defines some keys based on your current keyboard layout (QWERTY, Colemak, Dvorak, etc).

**Comment by mrkkrp** [comment]
@xahlee, I've improved my `README.md` file, thanks again for your feedback. I'm closing this.

**Comment by xahlee** [comment]
@mrkkrp thanks. I haven't made a collection of emacs key packages... but it's basically what you've collected. Was thinking, to write a summary about each like you did.

**Comment by mrkkrp** [comment]
@xahlee, By the way, I've asked a question on Emacs StackExchange: https://emacs.stackexchange.com/questions/16641/what-packages-are-available-for-modal-editing

While I don't think people will come with something I don't know already, it's a good question anyway. You could post an answer there mentioning `xah-fly-key`.
