### ISSUE TITLE
Improve docs strings of translating commands created by the package

### ISSUE THREAD

**Issue by mrkkrp** [mrkkrp/modalka#10]
We need nicer output with <kbd>C-h k</kbd> (`describe-key`) command. @phil-s, this is a separate issue to keep track of the problem.

**Comment by mrkkrp** [comment]
@phil-s, Now it should look OK. Thank you for [this answer](https://emacs.stackexchange.com/questions/22625/is-it-possible-to-attach-generated-doc-string-to-a-lambd), as I understand you are `phils` on Emacs Stack Exchange.

**Comment by phil-s** [comment]
Yes indeed, and you're welcome.

One more improvement -- I've just checked and confirmed that a docstring *can* be dynamic. Info node "(elisp) Accessing Documentation" says of `documentation-property`:

> If the property value isn’t ‘nil’, isn’t a string, and doesn’t refer to text in a file, then it is evaluated as a Lisp expression to obtain a string.

Hence if we backquote the docstring form (with the two keys pre-evaluated), the key binding help will always be correct, even if target-key's binding changes.

```
`(format "This command translates %s into %s, which calls ‘%s’."
              (key-description ,actual-key)
              (key-description ,target-key)
              (key-binding     ,target-key))
```

which works as advertised in my tests.

**Comment by phil-s** [comment]
In fact, I presume you could use that ability to incorporate the docstring for the target command.

**Comment by mrkkrp** [comment]
I have updated the code to make doc strings dymanic. It works, thank you for the proposition.

**Comment by phil-s** [comment]
Cool. I'm curious that you've stuck with ```
which calls ‘%s’.
``` rather than ```
which calls `%s'.
``` as the latter enables people to jump from this help to the help for the target command.

I can't figure out any reason to avoid including the link.

**Comment by mrkkrp** [comment]
@phil-s, Hey, but single quotes do the trick as well (at least here, on Emacs 25). Don't they work for you?

**Comment by phil-s** [comment]
Ah, I see! No, that format doesn't work for me (24.5). In Emacs 24 and below I believe it needs it to be the classic `' quoting style.

**Comment by mrkkrp** [comment]
I'll revert this then.

**Comment by mrkkrp** [comment]
@phil-s, Now link should work for everyone.

**Comment by phil-s** [comment]
Looks good :) Thanks!
