### ISSUE TITLE
Question: How to integrate with multiple cursors?

### ISSUE THREAD

**Issue by sriramkswamy** [mrkkrp/modalka#13]
Let's say I have the following maps -

```
(modalka-define-kbd "j" "C-n")
(modalka-define-kbd "k" "C-p")
(modalka-define-kbd "h" "C-b")
(modalka-define-kbd "l" "C-f")
```

I use [region-bindings-mode](https://github.com/fgallina/region-bindings-mode) and [multiple-cursors](https://github.com/magnars/multiple-cursors.el) to create a bunch of cursors. If I try to use the above bindings and press, say `h`, I get a prompt as to whether use this `modalka-translation` for all cursors or just one? If I ask it to use it for all the cursors, then the result is that all the cursors are merged into one but pressing `C-b` causes no problem.

How can I integrate modalka movements with multiple cursors?

**Comment by mrkkrp** [comment]
Can't advise anything, I use neither `region-bindings-mode` nor `multiple-cursors`.

**Comment by sriramkswamy** [comment]
Alright, thank you!

**Comment by DogLooksGood** [comment]
@mrkkrp Hi, what would you do if you want to edit multiple lines with one operation.

**Comment by mrkkrp** [comment]
Either create a macro (with `F3` and `F4`) or create a new command in Emacs lisp. I have a custom command to add something at the end of every line, for example. I also use rectangular selection and the associated commands a lot. But this is just my style of editing.

**Comment by DogLooksGood** [comment]
@mrkkrp Thanks!
