### ISSUE TITLE
bind to macros and commands

### ISSUE THREAD

**Issue by valerdi** [mrkkrp/modalka#17]
is there a way to bind keys to macros and commands? or is only to other keys?

**Comment by mrkkrp** [comment]
Please read the readme, it answers your question about bindings commands:

https://github.com/mrkkrp/modalka#how-to-define-translations

> If you want to bind a command in `modalka-mode` without performing a keybinding translation, remember that `modalka-mode` is just a normal minor mode which has an associated key map called `modalka-mode-map`. So you can do the following:
>
> ```haskell
> (define-key modalka-mode-map (kbd "Q") #'my-command)
> ```

As for binding keys to macros, you need to clarify what you mean by that. Sure you can make a key work as F4 that usually runs keyboard macros, but I don't see much value in that.

**Comment by valerdi** [comment]
oh, sorry, i missed that part. When i said macros i meant like record a macro with F3 <some keys> F4, save it with name-last-kbd-macro, and then reuse it with a key. I realized now that we can use

(define-key modalka-mode-map (kbd "Q") #'my-command)

with my-command being execute-kbd-macro. Thanks for the link.
