### ISSUE TITLE
Creating more than 2 modes

### ISSUE THREAD

**Issue by kbdluv** [mrkkrp/modalka#18]
Sorry if I didn't understand the docs correctly, but I couldn't be sure whether modalka creates exactly two modes (normal / insert), or if I could use it to create any number of modes I want with different keybindings in each (normal / movement / insert / tree / bananas).

If the former, is there anything you can point me to that would allow me to achieve the latter? Thank you!

**Comment by mrkkrp** [comment]
Unfortunately, this is not what Modalka is designed for. It's a minor mode that can be either turned on or turned off, that amounts to having only two modes.

**Comment by kbdluv** [comment]
Ok, good to know. Thanks!
