### ISSUE TITLE
Extended keychords not working

### ISSUE THREAD

**Issue by ibnishak** [mrkkrp/modalka#19]
I tried to use `(modalka-define-kbd "s l" "C-a C-SPC C-e")` which did not work. I also tried `(modalka-define-kbd "s l" "<home> C-SPC <end>")` which failed to translate too. While `(modalka-define-kbd "c c" "C-c C-c")` works. 

Emacs version: 25.3
OS: Manjaro linux

**Comment by mrkkrp** [comment]
Well, that's right, you bind a key to some other key. The target key should be a binding corresponding to one command, while `"C-a C-SPC C-e"` looks like three commands to me. You should use Emacs macros instead. Or define your own little helper and bind that (this is what I would do).

Here is what you could do:

```emacs-lisp
(defun my-little-helper ()
  (interactive)
  (beginning-of-line)
  (set-mark-command nil)
  (end-of-line))

(define-key modalka-mode-map (kbd "s l") #'my-little-helper)
```

Hope that helps.

**Comment by ibnishak** [comment]
thank you for clearing that up.
