### ISSUE TITLE
modalka-global-mode shouldn't affect the minibuffer

### ISSUE THREAD

**Issue by Wilfred** [mrkkrp/modalka#2]
I've noticed that `modalka-global-mode` means modalka is even active in the minibuffer. I think this is surprising (it took me a moment to work out 'why can't I type e?') and modalka shouldn't change behaviour in this case. What do you think?

**Comment by mrkkrp** [comment]
@Wilfred, thanks for the feedback. I don't use it globally so I missed this, sorry. This will be fixed tomorrow along with other minor corrections, I'm done for today :-)

**Comment by mrkkrp** [comment]
@Wilfred, this should have been fixed in 4b33b37. Note that now it's not activated in minibuffer and you can also add symbols to `modalka-excluded-modes` to avoid enabling `modalka-mode` with some major modes.

**Comment by Wilfred** [comment]
Works nicely, thank you :)
