### ISSUE TITLE
Cursor color

### ISSUE THREAD

**Issue by apnewberry** [mrkkrp/modalka#23]
I'm using this hook to switch my cursor color, but it can be unreliable, I wonder how you'd feel about including modalka-cursor-color in the definition of the minor mode, to supplement modalka-cursor-type?

```elisp
(add-hook 'modalka-mode-hook
	  '(lambda ()
	     (if modalka-mode
		 (set-cursor-color "Purple")
	       (set-cursor-color "Green"))))
```

**Comment by mrkkrp** [comment]
Why is this unreliable?

**Comment by apnewberry** [comment]
Pretty often pretty changes to purple even though I'm not in `modalka-mode`. I haven't figured out what's causing it yet.

**Comment by mrkkrp** [comment]
This should be investigated, the approach with hooks is probably better here.

**Comment by phil-s** [comment]
`set-cursor-color` sets a frame parameter.  That's clearly not what you want to do.

**Comment by phil-s** [comment]
For GUI Emacs, you can use `face-remap-add-relative` to modify the `cursor` face on a buffer-local basis.

(In a terminal, the `cursor` face is irrelevant, as the terminal controls the cursor.)
