### ISSUE TITLE
How to do mode specific binding?

### ISSUE THREAD

**Issue by DogLooksGood** [mrkkrp/modalka#27]
For example, I may want to bind "D" to "C-d" in prog-mode, but "D" to "D" in dired-mode.

**Comment by mrkkrp** [comment]
You could register hooks on activation of those modes which would set the bindings in `modalka-mode-map`.

**Comment by DogLooksGood** [comment]
Is that I can only use `modalka-define-kbd` for global settings?

**Comment by mrkkrp** [comment]
The keymap is stateful. If you set it once it'll be global, if you add something that overwrites it for specific modes, it'll be more dynamic. `modalka-defnie-kbd` just sets a keybinding.

**Comment by mrkkrp** [comment]
Does this answer your question?

**Comment by DogLooksGood** [comment]
Sorry, still not clear yet. I think there's only one modalka-mode-map, and this is available on every buffer if modalka mode is enabled. If I bind a key in hook, it will affect the behavior in other mode, right?

like if I bind "a" to "C-a" in my init.el, and bind "a" to "C-b" in `dired-mode-hook`. It will cause all "a" translate to "C-b" in modalka-mode, right?

**Comment by mrkkrp** [comment]
Hmm, indeed. I must admit I have never used Modalka like this. What you could do is: set mode-specific bindings in `dired-mode-map` and they will overwrite the global key bindings, especially if you set them in `dired-mode-hook`. Or you could keep key translation in Modalka constant but make the target key perform different functions in different modes.

**Comment by DogLooksGood** [comment]
Thanks! this make sense.
