### ISSUE TITLE
How to change modalka-bindings in a per mode basis?

### ISSUE THREAD

**Issue by saheratarch** [mrkkrp/modalka#28]
First, I'd like to thank you for modalka. It's very simple yet very powerful.

Here is my issue: I'd like to bind keys in `modalka-map` in per a mode basis.
For example: suppose that I want the key `x` to be bound to `cmd1` in  `mode1` and to be bound in `cmd2` in `mode2`.

I have tried hooks, but they change `modalka-map` globally.
Is there something like a modalka-local-map which sets `modalka-map` in a per buffer basis?

**Comment by saheratarch** [comment]
One work around for this is found in 
http://ergoemacs.org/misc/xah-fly-keys_customization.html
Here is the relevant code:

```
(defun my-wrapper ()
  "call different commands depending on what's current major mode."
  (interactive)
  (cond
   ((string-equal major-mode "x1-mode") (x1-cmd))
   ((string-equal major-mode "x2-mode") (x2-cmd))
   ;; more major-mode checking here

   ;; if nothing match, do nothing
   (t nil)))
```
This is a bit hack-y. Is there a neater method?

**Comment by mrkkrp** [comment]
This is not exactly what modalka was created for. Think about it this way: modalka is just an easier way to press the keys. So you can have per-mode bindings that do mode-specific things but then you can just define the appropriate translations that will result in different functions being called in the end, depending on the major mode. For example, let's say you have `C-c x` which does A in `mode-a` and B `mode-b`. Then if you define the mapping `c x` for `C-c x` then you get `c x` in modalka mode which performs action A in `mode-a` and action B in `mode-b`.

**Comment by saheratarch** [comment]
I 

> This is not exactly what modalka was created for. Think about it this way: modalka is just an easier way to press the keys. So you can have per-mode bindings that do mode-specific things but then you can just define the appropriate translations that will result in different functions being called in the end, depending on the major mode. For example, let's say you have `C-c x` which does A in `mode-a` and B `mode-b`. Then if you define the mapping `c x` for `C-c x` then you get `c x` in modalka mode which performs action A in `mode-a` and action B in `mode-b`.

I see, in this case, I'll begin changing my config so that modalka bindgs keys into other keys instead of functions. Thank you for answering my question. Feel free to close this issue.

**Comment by saheratarch** [comment]
I'd like to add that ryo-modal has this functionality: https://github.com/Kungsgeten/ryo-modal
