### ISSUE TITLE
A modalka mode hook when modalka is disabled but not enabled?

### ISSUE THREAD

**Issue by saheratarch** [mrkkrp/modalka#29]
Is it possible to have a modalka mode hook that only works when you turn modalka mode off?
The variable `modalka-mode-hook` works for toggling modalka on and off

**Comment by saheratarch** [comment]
I've solved it. Here is the solution:

    (defun push-mark-when-modalka-off ()
    "pushes mark when `modalka-mode' is turned off"
    (interactive)
    (when (eq modalka-mode nil) (push-mark)))

What this function does is check if modalka mode is off, and if it is it pushes the mark. otherwise it does nothing.
Now I then add this function to a `modalka-mode-hook` and now every time I exit (but not enter) modalka mode the mark is pushed. Which is the desired behavior.

Feel free to close this issue

**Comment by phil-s** [comment]
Note that this is how *all* minor mode hooks work -- you simply test the minor mode's variable to see whether it is being enabled or disabled.

Typically you would write:

    (if modalka-mode
        ...enabling...
      ...disabling...)

In your case you could write:

    (when (eq modalka-mode nil) ...)

as:

    (unless modalka-mode ...)
