### ISSUE TITLE
Exit modalka-mode programatically

### ISSUE THREAD

**Issue by rsuhada** [mrkkrp/modalka#7]
When in modalka mode, I'd like to hit space and 1. exit into insert mode and 2. insert a space. This is my attempt, except I can't figure out how to exit modalka programatically:

    (defun exit-on-space ()
       (interactive)
       (cond
        (modalka-mode
         (modalka-global-mode nil)
         (insert " ")
         )))

     (define-key modalka-mode-map (kbd "SPC") #'exit-on-space)

**Comment by mrkkrp** [comment]
This should do the trick (not tested):

```emacs-lisp
(defun exit-on-space ()
  (interactive)
  (modalka-mode 0)
  (insert-char 32))
```

**Comment by mrkkrp** [comment]
BTW, if you type <kbd>C-h f modalka-mode RET</kbd>, then Emacs will tell you how to call the function and which arguments you can pass to it.

**Comment by rsuhada** [comment]
It works - thank you!
